version: "3.8"

services:
  app:
    container_name: infotecsTechTask
    build:
      context: ..
      dockerfile: deployments/dockerfile
    image: infotecsTechTask:latest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB_NAME: "${POSTGRES_DB_NAME}"
      POSTGRES_SSL_MODE: "${POSTGRES_SSL_MODE}"
      POSTGRES_MAX_OPEN_CONNS: "${POSTGRES_MAX_OPEN_CONNS}"
      POSTGRES_MAX_IDLE_CONNS: "${POSTGRES_MAX_IDLE_CONNS}"
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"